import { Inter } from "next/font/google";
import "./globals.css";
import ThemeRegistry from "@/app/ThemeRegistry";
import Header from "@/components/Header";
import { Container } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeRegistry options={{ key: "mui" }}>
          <Header />
          <Container>{children}</Container>
        </ThemeRegistry>
      </body>
    </html>
  );
}
